### ISSUE TITLE
Listar atividades existentes

### ISSUE THREAD

**Issue by tbbruno** [miggelucas/HomeTask#1]
## Historia de Usuária

Como usuária, eu gostaria de poder visualizar as minhas atividades numa lista para poder me lembrar posteriormente.

## Criterios de Aceitação

**1. Visualizar lista ao abrir o app**
**DADO** que eu baixei o app
**QUANDO** eu abro ele
**ENTAO** eu me deparo com a tela de lista

**2. Lista de atividades ja populada**
**DADO** que eu ja tenho atividades cadastradas
**QUANDO** eu abro vejo a lista de atividades
**ENTÃO** as atividades são listadas em ordem de adição

**3. Lista de atividades não populada**
**DADO** que eu não tenho nenhuma atividade cadastrada
**QUANDO** eu abro a tela de lista de atividades
**ENTAO** eu vejo uma mensagem de estado vazio

**Comment by miggelucas** [comment]
Xá comigo
